version: "3.2"

services:
  reservation:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
    command: symfony server:start --port=8000 --no-tls --allow-http
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reservations_api
      POSTGRES_USER: iannis_api
      POSTGRES_PASSWORD: iannis
    volumes:
      - postgres_data:/var/lib/postgresql/datapostgresql/data:rw
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres_data:
